[project]
name = "C23186-ordenamientos"
version = "0.1.0"
description = "Proyecto de análisis de algoritmos de ordenamiento con contadores"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "matplotlib",
    "numpy",
]
